for number in range(2, 9, 2):
    print(number)
'''
 This example demonstrates the use of range() and a for loop to generate and print a sequence of numbers.
 The range(2, 9, 2) generates a sequence of numbers starting from 2 up to, but not including, 9, with a step size of 2.
 This results in the sequence [2, 4, 6, 8].
 The 'for' loop iterates over this sequence, and during each iteration, the 'number' variable holds the current value from the sequence.
 The print() function is then used to output the value of 'number' to the screen.
 The goal of this example is to show how to use range() to create a custom sequence of numbers and how to use a loop
 to process and display these numbers without manually specifying each one.
 Key elements explained:
 1. 'number': This is an integer variable that stores the current value from the sequence generated by range().
    - During each iteration, 'number' takes on the values 2, 4, 6, and 8.
    - The type of 'number' is 'int'.
 2. range(start, stop, step): The range function generates a sequence of numbers based on the given parameters.
    - 'start' = 2: This is the first number in the sequence.
    - 'stop' = 9: This is the endpoint where the sequence stops, but it does not include this value.
    - 'step' = 2: The numbers will increase by 2 in each iteration (for example,, 2, 4, 6, 8).
 3. print(): The built-in print function outputs the current value of 'number' to the console.
    - This function is called in each loop iteration to display the current value of 'number'.
 4. range(2, 9, 2): This generates the sequence [2, 4, 6, 8], which is used by the loop.
   - The loop will iterate through this sequence, and in each iteration, 'number' will take the next value in the sequence.
 5. for number in range(2, 9, 2): The 'for' loop iterates over the sequence generated by range().
    - On each iteration, the value of 'number' changes to the next number in the sequence, and that value is printed to the screen.
In summary, the example creates a sequence of numbers (2, 4, 6, 8) using range() and prints each of these values
through a for loop. This is useful when you need to process a sequence of numbers without manually specifying each value.
'''
